### ISSUE TITLE
istioctl authn is deprecated in istio 1.7.3

### ISSUE THREAD

**Issue by jolguk** [Azure-Samples/aks-voting-app#10]
**Is this an issue or feature request?**

```
[ ] Issue x
[ ] Feature request
```

# Issue
The section to check that mutual TLS is applied fails because istioctl authn is deprecated in istio 1..7.3
**Which component and version?**
istio 1.7.3
**What happened?**
I am using istio 1.7.3 as advised in the docs on page https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux . When using the canary scenario in this codebase, when you have applied the TLS policies you can't use the provided commands to check it is working as istioctl authn is deprecated at this version. 

**What did you expect to happen?**

**Steps to reproduce the issue** 
kubectl get pod -n voting -l app=voting-app | grep Running | cut -d ' ' -f1 | xargs -n1 -I{} istioctl authn tls-check {}.voting voting-analytics.voting.svc.cluster.local
Error: unknown command "authn" for "istioctl"

Did you mean this?
        authz

Run 'istioctl --help' for usage.
Error: unknown command "authn" for "istioctl"

**Anything else we need to know?**

# Feature request

**What feature/behaviour/change would you like to see?**
The istioctl command changed to cater for current tls behaviour.

**Comment by paulbouwer** [comment]
Thank you for submitting the issue @jolguk. Apologies for the delay.

We have decided to retire the existing [Istio canary documentation](https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-scenario-routing) in the AKS docs. Customers are better served leveraging components like [Flagger](https://flagger.app/) for this capability. This means that we will also be [removing](https://github.com/Azure-Samples/aks-voting-app/pull/12) the scenario assets from this repo.
