### ISSUE TITLE
Docker-compose for local run

### ISSUE THREAD

**Issue by yulia-meijs** [Azure-Samples/aks-voting-app#15]
**Is this an issue or feature request?**

```
[ ] Issue
[x] Feature request
```

# Issue

**Which component and version?**

**What happened?**

**What did you expect to happen?**

**Steps to reproduce the issue** 

**Anything else we need to know?**

# Feature request

**What feature/behaviour/change would you like to see?**

Docker-compose for local run

**Comment by paulbouwer** [comment]
Implemented by #16
